### ISSUE TITLE
data not showing up

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#44] opened 2016-11-25 12:37 UTC
Hi @abyot ! I have entered my population data and situation indicators using the standard data entry module. I was trying to visualize them to see some of the legends I set up but I'm not finding any data in the system even though it's there when I go to data entry. I ran analytics and cleared my cache. 

![image](https://cloud.githubusercontent.com/assets/10057077/20625459/d31acc8c-b313-11e6-9655-0c9e6110d577.png)

![image](https://cloud.githubusercontent.com/assets/10057077/20625542/3a8bdc62-b314-11e6-902f-415fd2b169c0.png)

**Comment by abyot** [comment] 2016-11-25 12:54
Hi @kreinhardt,

That is because you have "Prevalence of stunting among children 6-59 months" aggregation type set to none. Changed that to sum and got this...

![image](https://cloud.githubusercontent.com/assets/4967749/20625803/bf781b6a-b315-11e6-9850-2fd9293a0411.png)

Also, you have set district, province and national as aggregation levels. This has a huge implication - it means there will be no vertical aggregation i.e. National level data will be whatever entered at national level - not the sum (or average depending on the aggregation type) of those entered below levels and selected one. Is this the correct scenario you want?

**Comment by kreinhardt** [comment] 2016-11-25 12:58
Ohhh! Ok!

The situation indicators are a special case because the data has already been analysis and I am entering it as a percentage. Because of this we cannot add or average the data across org units. That is why I set the aggregation level to all and entered situation indicator data at the district, province and national levels. 

For the target group data, I do want to aggregate from the district level so I left the aggregation level empty and the aggregation type as sum.

**Comment by abyot** [comment] 2016-11-25 13:02
ok, good.

**Comment by kreinhardt** [comment] 2016-11-25 13:27
the data is showing up now. However, now I have a question about the GIS module. I was able to open as a map but the legend that I set to the data element is not appearing. Just a default one. I assumed that I could select a legend to always be applied by default to a particular data element. 

I am also having an issue saving - when I click save - nothing happens. 

![image](https://cloud.githubusercontent.com/assets/10057077/20626622/3d52e8c6-b31b-11e6-962c-a8613ed918f0.png)

**Comment by abyot** [comment] 2016-11-25 13:59
I see... the red thing to the right is not a good thing.

But can you build the map from scratch - not open this chart as map - and see what happens?

**Comment by kreinhardt** [comment] 2016-11-25 16:42
I tried to make the map again but it just says no values!

![image](https://cloud.githubusercontent.com/assets/10057077/20631392/772e5952-b336-11e6-9165-63015441f07c.png)

**Comment by kreinhardt** [comment] 2016-11-28 12:23
Hi @abyot - just checking if you have been able to look into this? I'm also having trouble saving my graphs:

![image](https://cloud.githubusercontent.com/assets/10057077/20668202/dcd6b96e-b56d-11e6-9dc8-d7afa1f12c45.png)

**Comment by abyot** [comment] 2016-11-28 12:45
Hi @kreinhardt 

I am not able to reproduce... for example see the link below which I am able to save

http://109.237.25.74:9090/sunpmt/dhis-web-visualizer/?id=vwfN6HFZR07

Can you tell me the exact steps to reproduce?

**Comment by kreinhardt** [comment] 2016-11-28 13:25
I was trying to edit a graph that I had saved... all I changed was the order of the bars and then I wasn't able to save it. 

This is also still happening with the maps.... both when I open a chart as a map and when I start the map from scratch.

**Comment by abyot** [comment] 2016-12-18 09:23
Saving maps is now working... however there is a little issue when editing a saved map (favorite) and then saving it back... this will be fixed.

**Comment by kreinhardt** [comment] 2016-12-19 08:00
ok! Thanks @abyot

**Comment by kreinhardt** [comment] 2017-01-09 11:30
Hi Abyot - I wanted to follow up on this issue. I have noticed that pivot tables are not opening again once saved or not showing up in the dashboard when added. (Maps are showing up)

**Comment by kreinhardt** [comment] 2017-01-19 08:49
Hi Abyot - can you please provide an update on the maps and pivot table aspects. I still have not been able to update maps or save pivot tables. I would like to be able to have these working before finalizing the demo.

**Comment by abyot** [comment] 2017-01-22 23:05
This seems to be fixed. Please check and let me know.

**Comment by kreinhardt** [comment] 2017-01-23 14:50
It looks like I can open, edit and save a map now. However, I still cannot rename a map - this is what happends:
![image](https://cloud.githubusercontent.com/assets/10057077/22208020/a572647e-e181-11e6-8722-520ac0ea6a4a.png)

It looks like pivot tables and graphs are working though.

Thanks.

**Comment by abyot** [comment] 2017-02-15 11:50
It is now possible to rename.

**Closed** 2017-02-15 11:50 UTC
Labels: help wanted, question

**Comment by kreinhardt** [comment] 2017-02-15 14:27
great! thank you!
